name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  all-cli-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn build
      - run: yarn test:jest
      - run: yarn lint
      - run: yarn check-format
      - run: yarn check-types
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14.x'
      - uses: cypress-io/github-action@v2
        with:
          command: yarn e2e:ci
          build: yarn build
          start: yarn serve
